<link rel="manifest" href="/Blog/manifest.json">
<link href="https://fonts.googleapis.com/css?family=Noto+Serif+SC:300,400,500,600,700&display=swap&subset=chinese-simplified" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Kalam:300,400,700&display=swap&subset=devanagari,latin-ext" rel="stylesheet">
{# 注释
<link href="https://fonts.googleapis.com/css?family=Ma+Shan+Zheng&display=swap&subset=chinese-simplified" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Noto+Serif:400,700&display=swap&subset=latin-ext,vietnamese" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Source+Code+Pro:200,300,400,500,600,700,900&display=swap&subset=latin-ext" rel="stylesheet">
#}
{# 支持移动端自适应 #}
<meta name="viewport" content="width=device-width"> 